INSERT INTO DRIVER_DETAILS (ID, ADDITIONAL_DRIVERS, ADDRESS_LINE1, ADDRESS_LINE2, CITY,
                    COMMERCIAL_USE, CURRENT_VALUE, ENGINE_SIZE, FINAL_QUOTE_AMOUNT,
                    FIRST_NAME, LAST_NAME, OUTSIDE_STATE_USE, POSTCODE, PREFIX,
                    DATE_REGISTERED, TELEPHONE_NUMBER, VEHICLE_BODY_TYPE)
VALUES (1, 1, '221b', 'Baker Street', 'London', 'Yes',
        17432.84, '2000', 447.216, 'Sherlock', 'Holmes',
        'Yes', 'NW1 6XE', 'Dr', '2000-04-03',
        '01234567891', 'Coupe'
       );

INSERT INTO DRIVER_DETAILS (ID, ADDITIONAL_DRIVERS, ADDRESS_LINE1, ADDRESS_LINE2, CITY,
                    COMMERCIAL_USE, CURRENT_VALUE, ENGINE_SIZE, FINAL_QUOTE_AMOUNT,
                    FIRST_NAME, LAST_NAME, OUTSIDE_STATE_USE, POSTCODE, PREFIX,
                    DATE_REGISTERED, TELEPHONE_NUMBER, VEHICLE_BODY_TYPE)
VALUES (2, 2, '742', 'Evergreen Terrace', 'Springfield', 'No',
        5500.50, '1600', 405.504, 'Marge', 'Simpson',
        'Yes', '89011', 'Mrs', '1987-12-17',
        '10987654321', 'Hatchback'
       );

INSERT INTO DRIVER_DETAILS (ID, ADDITIONAL_DRIVERS, ADDRESS_LINE1, ADDRESS_LINE2, CITY,
                    COMMERCIAL_USE, CURRENT_VALUE, ENGINE_SIZE, FINAL_QUOTE_AMOUNT,
                    FIRST_NAME, LAST_NAME, OUTSIDE_STATE_USE, POSTCODE, PREFIX,
                    DATE_REGISTERED, TELEPHONE_NUMBER, VEHICLE_BODY_TYPE)
VALUES (3, 2, '15', 'Yemen Road', 'Yemen', 'No',
        8000.00, '3000', 617.76, 'Chandler', 'Bing',
        'Yes', '11111', 'Mr', '1998-02-26',
        '00000000001', 'Cabriolet'
       );

INSERT INTO DRIVER_DETAILS (ID, ADDITIONAL_DRIVERS, ADDRESS_LINE1, ADDRESS_LINE2, CITY,
                    COMMERCIAL_USE, CURRENT_VALUE, ENGINE_SIZE, FINAL_QUOTE_AMOUNT,
                    FIRST_NAME, LAST_NAME, OUTSIDE_STATE_USE, POSTCODE, PREFIX,
                    DATE_REGISTERED, TELEPHONE_NUMBER, VEHICLE_BODY_TYPE)
VALUES (4, 1, '42', 'Wallaby Way', 'Sydney', 'Yes',
        25000, '2500', 598.95 , 'Philip', 'Sherman',
        'Yes', 'SY12 3AU', 'Dr', '2003-10-10',
        '61412345678', 'Estate'
       );
