INSERT INTO driver (ID, ADDITIONAL_DRIVERS, ADDRESS_LINE1, ADDRESS_LINE2, CITY,
                    COMMERCIAL_PURPOSE, CURRENT_VALUE, ENGINE_SIZE,	FIRST_NAME,
                    LAST_NAME, OUT_OF_REGISTERED_STATE, POSTCODE_OR_ZIP, PREFIX
    ,REGISTRATION_DATE, TELEPHONE_NUMBER, VEHICLE_TYPE)
VALUES (1, 1, '221b', 'Baker Street', 'London', 'Yes',
        '£20,001 to £30,000', '2000', 'Sherlock', 'Holmes',
        'Yes', 'NW1 6XE', 'Dr', '2000-04-03',
        '01234567891', 'Coupe'
       );